### ISSUE TITLE
Accounts are not working :(

### ISSUE THREAD

**Issue by LARSABI** [I2rys/opengen-bot#2]
Hey, not a Single Account is working.. Also every password has a ( ! ) at the end. Am i making something wrong?

**Comment by I2rys** [comment]
Hello @LARSABI,
To clarify things up, **opengen-bot** accounts are not tested If they work also about the every password has a **!** at the end. I think something is wrong because I tested **opengen-bot** and the passwords does not have **!** in their last part always.

Can you please say what type of account did you generate? Also did you modify the code?

**Comment by LARSABI** [comment]
I created only Spotify Accounts. Been looking for a working generator for a Long Time. 
No i did not modified the Code.

**Comment by I2rys** [comment]
> I created only Spotify Accounts. Been looking for a working generator for a Long Time. No i did not modified the Code.

I'm really sorry for the problem as I will not be able to resolve your problem in getting working Spotify accounts using **opengen-bot** as I have not tested **opengen-bot** and I do not have any control to **https://opengen.dpkghub.com/**
